// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-1:6f92f236-6136-4635-8989-cff9f424a327",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VA73nV7l7",
    "aws_user_pools_web_client_id": "22c37vklgkuuojpitrgdn26o9n",
    "oauth": {}
};


export default awsmobile;
